server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web: debug
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/craftlink
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update