app:
  frontend-url: http://localhost:5173
  database:
    seed: true

auth:
  jwt:
    secret: ${JWT_ACCESS_TOKEN_SECRET}
    access-token:
      expiration-seconds: 60
  cookie:
    refresh-token:
      expiration-seconds: 604800
      domain: localhost
      path: /
      http-only: true
      secure: false
      same-site: Strict

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web: debug
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/craftlink
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
