logging:
  level:
    org:
      springframework:
        web: warn
      hibernate:
        SQL: off
        orm:
          jdbc:
            bind: off

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: none 