app:
  frontend-url: http://localhost:3000

auth:
  jwt:
    expiration-time: 60000
    secret: ${JWT_ACCESS_TOKEN_SECRET}
  cookies:
    refresh-token:
      expiration-time-in-seconds: 180000
      domain: localhost
      path: /
      httpOnly: true
      isSecure: false

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web: debug
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/craftlink
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update